[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts=lib/chainlink-brownie-contracts/contracts/", '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']

[invariant]
runs = 128 # Number of runs
depth = 128 # Number of calls in a single run
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config